---
# handlers file for mithings-host

# - name: systemd-docker-reload
#   systemd: state=restarted daemon_reload= yes name=docker

- name: reboot_server
  command: shutdown -rf now
  async: 0
  poll: 0
  ignore_errors: true