development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASS'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>

production: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASS'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>

test: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RAILS_DB_NAME'] %>
  pool: 5
  username: <%= ENV['RAILS_DB_USER'] %>
  password: <%= ENV['RAILS_DB_PASS'] %>
  host: <%= ENV['RAILS_DB_HOST'] %>
  port: <%= ENV['RAILS_DB_PORT'] %>