---
# tasks file for mithings-host (ubuntu)

- name: update system packages
  apt: upgrade=dist

- name: install required packages for docker
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https 
    - ca-certificates
    - "linux-image-extra-{{ ansible_kernel }}"
    - python-setuptools


- name: install the required apt-key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: install docker repo
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: update cache
  apt: update_cache=yes

- name: purge old repo
  apt: name=lxc-docker state=absent purge=yes

- name: install docker
  apt: name=docker-engine state=present

- name: add docker group
  group: name=docker state=present

- name: add jj user to docker group
  user: name=jj groups=docker append=yes

- name: enable cmem support
  lineinfile: dest=/etc/default/grub state=present regexp="^GRUB_CMDLINE_LINUX" line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
  notify: reboot_server

- name: start docker
  service: name=docker enabled=yes state=started

- name: install pipp
  easy_install:
    name: pip
    state: latest

- name: install docker-py
  pip:
    name: docker-py
    version: 1.9.0

# Not sure if I ever got this working^jj
- name: setup rancher
  docker_container:
    privileged: yes
    volumes:
      - "/var/lib/rancher:/var/lib/rancher"
    command: "https://rancher.mithings.pw/v1/scripts/57536EB12796613CB07B:1476921600000:s71UHZLqPJ4rTnft6BVwuDbUs"
    image: rancher/agent:v1.0.2
    name: "rancher-sets-this"